### ISSUE TITLE
Edit Tab: Critical Bug — title values are not escaped!

### ISSUE THREAD

**Issue by fijha** [adrianbj/BatchChildEditor#10]
`$cp->title` needs to be escaped with `htmlspecialchars($cp->title)`

**BatchChildEditor.module, line 757**:

`<input id="'.$cp->id.'" type="text" name="individualChildTitles['.$cp->id.']" value="'.$cp->title.'" style="width:100%" '. (!$cp->editable() ? " readonly" : "") . ' />`

— this messed up some of my pages that has quotes in the title!

**Comment by adrianbj** [comment]
Thanks for picking up on that @fijha - much appreciated.

It's fixed in the latest version, although I used:
`htmlspecialchars($cp->title, ENT_QUOTES, "UTF-8")`
