### ISSUE TITLE
Getting exception error when editing a parent

### ISSUE THREAD

**Issue by lesaff** [adrianbj/BatchChildEditor#11]
```
Method Page::localName does not exist or is not callable in this context (in /wire/core/Wire.php line 476)
```

PW version: 3.0.42

**Comment by adrianbj** [comment]
Any chance you have multi-language installed, but not "LanguageSupportPageNames" ?

I think I maybe didn't account for that combination. Could you please confirm?

**Comment by lesaff** [comment]
You're right. That's what it was.

**Comment by adrianbj** [comment]
Should be fixed by https://github.com/adrianbj/BatchChildEditor/commit/4b11de433ba05880d64062ab84d6dd8415c4a04e

Please re-open if you still have any problems.

Thanks!
