### ISSUE TITLE
Edit Mode needs grid lines

### ISSUE THREAD

**Issue by gmclelland** [adrianbj/BatchChildEditor#12]
When in edit mode, I think it would be beneficial to include some styling that adds grid row lines to match the look of the Lister Mode.

Here is how it looks without the lines:
![image](https://user-images.githubusercontent.com/40570/35639924-58ed6542-0681-11e8-88df-b2738e8156a9.png)

Here is how it looks with the lines:
![image](https://user-images.githubusercontent.com/40570/35639951-6ce92f2c-0681-11e8-8257-6996e5f8f917.png)

**Comment by adrianbj** [comment]
Not sure if you agree or not, but I kinda feel like this is an issue with the UiKit theme and its styling of tables. The default theme looks like this:

![image](https://user-images.githubusercontent.com/871211/35640322-b2fffb54-0671-11e8-8381-bbebfe57e8a8.png)

What do you think?

**Comment by gmclelland** [comment]
Hmm... I'm not sure really.

It looks like unchecking this box adds the grid row lines in the UiKit theme.

![edit page about pw3 test 2018-01-31 12-37-21](https://user-images.githubusercontent.com/40570/35640722-a4b52de6-0683-11e8-88c5-113166cc727b.jpg)

Here it is with the grid row lines:
![edit page about pw3 test 2018-01-31 12-40-34](https://user-images.githubusercontent.com/40570/35640811-fb162cb2-0683-11e8-96bd-c4ab5d184e07.jpg)

**Comment by adrianbj** [comment]
Thanks for finding that - fixed in v1.8.5.

**Comment by gmclelland** [comment]
Glad I could help.  Thank you for the quick response!
