### ISSUE TITLE
Feature Request: Resolve internal values on CSV-Export

### ISSUE THREAD

**Issue by spackmat** [adrianbj/BatchChildEditor#15]
Hi, first. thanks for that nice module! 

I have a feature request for the CSV-Export: At the moment, only internal values are exported. This makes sense for usecases, where they are to be imported back to a PW-instance with the same template. But for other usecases, it doesn't. We have a place database and want to export the places to be used within other software. But the export only uses the internal values of ProcessWire like the ID of the select option for a select field instead of its readable representation. So I have to give along a detailed legend for what all those integers stand for and someone has to normalize the data within the CSV before it can be processed. And that legend approach doesn't work at all for related pages, where I need the page's title field to be exported instead its id.

So what I basically want is that I can choose if I want to export the human readable values of the fields or their internal numeric value:

    "Place category";Title;"Furnishing type"
    2;"03.2.003 Classroom";2
    1;"03.2.004 Auditorium";1

    "Place category";Title;"Furnishing type"
    "Classroom";"03.2.003 Classroom";"desks and chairs"
    "Auditorium";"03.2.004 Auditorium";"fixed seats"

I had expected the "Turns on output formatting for exported values." setting to switch between the variants, but in my case both export the same.

**Comment by adrianbj** [comment]
Hi @spackmat - thanks for the report. You are correct in assuming that the output formatting setting should work. It did for other fields, but not Select Options (these are weirdly built). I have fixed it now. Please check at your end and close if you're happy.

**Comment by spackmat** [comment]
@adrianbj Perfect, works. Thanks, that was really fast!
